apiVersion: apps/v1
kind: Deployment      
metadata:
  name: nginx
  labels:
    app: nginx          
spec:
  replicas: 1
  selector:
    matchLabels:        
      app: nginx
  template:
    metadata:
      labels:           #Etiquetas del pod
        app: nginx      
        version: 1.7.9  
    spec:
      containers:       #Definición de la imagen que se va a descargar
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80