apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 3
  ports:
  - port: 80
    protocol: TCP
    targetPort: 32593
  selector:
    app: nginx
  type: LoadBalancer
status:
  loadBalancer: {}
