apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: app
spec:
  containers:
    - image: nginx
      name: app
      volumeMounts:
        - name: configpvc #kokoref
          mountPath: "/data/app/config"
  volumes:
    - name: configpvc #kokoref
      persistentVolumeClaim:
        claimName: pvc01 # reference the pvc name (pv01)