apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: app
spec:
  volumes:
    - name: configpvc #kokoref
      persistenVolumeClaim:
        claimName: pv01 # reference the pvc name (pv01)
  containers:
    - image: nginx
      name: app
      volumeMounts:
        - mountPath: "/data/app/config"
          name: configpvc #kokoref